platform :ios, '7.1'

target 'UnDiaParaDar', :exclusive => true do
	pod 'Typhoon', '~> 2.3.1'
	pod 'PureLayout'	
	pod 'RestKit', '0.24.1'
	pod 'RETableViewManager', '~> 1.5.12'
	pod 'GCNetworkReachability', '~> 1.3'
	pod 'ExternalLibraries', :path => 'ExternalLibraries'
	pod 'GCNetworkReachability', '~> 1.3'
# Facebook!!!
	pod 'FBSDKLoginKit', '~> 4.1'
	pod 'FBSDKShareKit', '~> 4.7.1'
end

