platform :ios, '7.1'

target 'UnDiaParaDar', :exclusive => true do
	pod 'Typhoon', '~> 2.3.1'
	pod 'UIView+AutoLayout', '~> 1.1.0'
	pod 'RestKit', '~> 0.23.3'
	pod 'GCNetworkReachability', '~> 1.3'
	pod 'ExternalLibraries', :path => 'ExternalLibraries'
end

